import * as webjsx from 'webjsx';
// Imported directly from their owning submodules, not the ds/components.js
// barrel: the barrel re-exports 30+ submodules (voice, collab, calendar,
// editor/overlay-primitives, freddie, etc) that this kit never uses, and
// native unbundled ESM must fetch+parse every one of them to build the graph
// regardless of which names are actually imported -- measured live at 200+
// serial module requests for this page alone. Importing straight from the
// owning file keeps this kit's fetch graph proportional to what it renders.
import { Topbar, Crumb, Side, AppShell, Status, Lede, Chip, Heading } from 'ds/components/shell.js';
import { Panel } from 'ds/components/content.js';
import { AICat, AICatPortrait, flashComposerNote, ChatComposer, ChatSuggestions } from 'ds/components/chat.js';
import { mountKit } from 'ds/bootstrap.js';
const h = webjsx.createElement;

const FACES = {
    idle:    ` /\\_/\\\n( o.o )\n > ^ <`,
    happy:   ` /\\_/\\\n( ^.^ )\n > ~ <`,
    think:   ` /\\_/\\\n( -.- )\n > ? <`,
    pounce:  ` /\\_/\\\n( O.O )\n > ! <`
};

// Stub past-conversation rows so "history" reads as a project-tree group
// (parent + nested children) rather than a bare count chip. Static/reference
// data only — no persistence backing these in this kit. Trimmed to a single
// entry: the reference shows exactly one nested conversation row under the
// project folder, not a populated list — a sparse history is part of what
// keeps the empty-state canvas reading as genuinely empty on load.
const HISTORY = [
    { t: 'welcome to aicat', k: 'h0' }
];

// The seed transcript a first-time visitor would have generated by chatting
// already. NOT loaded into state.messages by default (see `state` below) —
// state.messages starts empty so the composer is the sole focal element on
// load, matching the reference's empty-state-first canvas. Reachable via the
// one HISTORY row and the "welcome" suggestion chip.
const WELCOME_MESSAGES = [
    { who: 'them', name: 'aicat', text: 'hi. I am **aicat**. I read fast and I knock things off shelves.', time: timeNow() },
    { who: 'them', name: 'aicat', parts: [{ kind: 'md', text: 'try one of these:\n\n- ask for `code` (react/python — pick a flavour)\n- ask for the **token pdf** or the **mascot image**\n- ask me to attach a *config file*\n- or just chat — I respond in markdown.' }], time: timeNow() }
];

const PRESETS = [
    { q: 'show me a small react component', k: 'code-react' },
    { q: 'show python prime sieve', k: 'code-py' },
    { q: 'explain prefers-reduced-motion', k: 'md-rm' },
    { q: 'send the v0.0.27 token sheet', k: 'pdf' },
    { q: 'paste the mascot art', k: 'image' },
    { q: 'link the design repo', k: 'link' },
    { q: 'attach a config file', k: 'file' },
    { q: 'tell me a joke about garbage collection', k: 'text' }
];

// 4-chip starter subset for the true empty state (see 'main-empty' below) --
// one representative prompt per reply modality (code / pdf / image / link)
// rather than all 8 PRESETS, so the empty canvas reads as a few clear
// starting points instead of a wall of chips competing with the composer.
const STARTER_KEYS = ['code-react', 'pdf', 'image', 'link'];
const STARTER_PRESETS = STARTER_KEYS.map((k) => PRESETS.find((p) => p.k === k));

const REPLIES = {
    'code-react': () => ({ parts: [
        { kind: 'text', text: 'sure — here\'s a tiny one:' },
        { kind: 'code', lang: 'jsx', filename: 'Greet.jsx',
          code: 'export function Greet({ name }) {\n  return <p>hi, {name} — =^.^=</p>;\n}\n\nexport default Greet;' }
    ] }),
    'code-py': () => ({ parts: [
        { kind: 'text', text: 'classic sieve, no imports:' },
        { kind: 'code', lang: 'python', filename: 'sieve.py',
          code: 'def primes(n):\n    sieve = [True] * (n + 1)\n    sieve[0] = sieve[1] = False\n    for i in range(2, int(n ** 0.5) + 1):\n        if sieve[i]:\n            for j in range(i * i, n + 1, i):\n                sieve[j] = False\n    return [i for i, p in enumerate(sieve) if p]\n\nprint(primes(50))' }
    ] }),
    'md-rm': () => ({ parts: [{ kind: 'md', text: '## prefers-reduced-motion\n\nmedia query that signals the user wants less animation. honour it:\n\n- short-circuit fade-ins\n- drop big translates\n- keep opacity-only if anything\n\n```css\n@media (prefers-reduced-motion: reduce) {\n  * { animation-duration: 0ms !important; }\n}\n```\n\n> opt out of motion, not out of feedback.' }] }),
    pdf: () => ({ parts: [
        { kind: 'text', text: 'here you go — `tokens-v0.0.27.pdf`:' },
        { kind: 'pdf', src: './sample.pdf', name: 'tokens-v0.0.27.pdf', size: 782 }
    ] }),
    image: () => ({ parts: [
        { kind: 'text', text: 'mascot, fresh from the loom:' },
        { kind: 'image', src: './sample-svg.svg', alt: '247420 mascot', caption: 'mascot · svg · favicon-derived' }
    ] }),
    link: () => ({ parts: [
        { kind: 'link', href: 'https://github.com/AnEntrypoint/design', host: 'github.com',
          title: 'AnEntrypoint/design',
          desc: 'design system for 247420 — layered surfaces, mono labels, pill radii.',
          thumb: './sample-square.png' }
    ] }),
    file: () => ({ parts: [
        { kind: 'text', text: 'config attached — drop it in `~/.config/aicat/config.json`.' },
        { kind: 'file', src: './sample.pdf', name: 'aicat.config.json', size: 412, kindLabel: 'JSON' }
    ] }),
    text: () => ({ parts: [{ kind: 'text', text: 'a generational gc walks into a bar. the bartender says, *you again?* gc says, **don\'t worry, I\'ll be young forever.**' }] })
};

// Truncate at a word boundary near `max` rather than a raw character cut, so
// the visible label keeps the last whole word instead of splitting mid-word
// (e.g. "send the v0.0.27 token…" instead of "send the v0.0.27 tok…"). The
// untruncated string is still passed separately as `ariaLabel` (app-shell.js)
// so screen-reader users get the full text regardless of where this cuts.
function truncateAtWord(text, max) {
    if (text.length <= max) return text;
    const cut = text.slice(0, max);
    const lastSpace = cut.lastIndexOf(' ');
    return (lastSpace > max * 0.5 ? cut.slice(0, lastSpace) : cut) + '…';
}

function classifyAndReply(text) {
    const t = text.toLowerCase();
    const map = [
        [/python|sieve|prime/, 'code-py'],
        [/code|react|component|function|jsx/, 'code-react'],
        [/reduced.motion|animat|motion/, 'md-rm'],
        [/pdf|token sheet|spec/, 'pdf'],
        [/image|mascot|picture|art/, 'image'],
        [/link|repo|github/, 'link'],
        [/file|config|attach/, 'file']
    ];
    for (const [re, k] of map) if (re.test(t)) return REPLIES[k]();
    return REPLIES.text();
}

// `phase` drives the transcript. AICat renders the happy path; `empty` is a
// fresh session, `error` is a model-side failure, `loading` is history being
// rehydrated. All three are reachable from the sidebar so they stay live
// reference surfaces rather than paths only a real outage would reveal.
const PHASES = ['ready', 'loading', 'empty', 'error'];

// Turn-shaped shimmer for history rehydration. Reuses .ds-event-row-skeleton +
// .ds-skel* (app-shell/files.css) — avatar / body / timestamp, same rhythm.
function TranscriptSkeleton() {
    return h('div', {},
        ...Array.from({ length: 5 }, (_, i) => h('div', { key: 'sk' + i, class: 'ds-event-row-skeleton' },
            h('span', { class: 'ds-skel ds-skel-icon' }),
            h('span', { class: 'ds-skel ds-skel-title' }),
            h('span', { class: 'ds-skel ds-skel-meta' })
        ))
    );
}

function TranscriptEmpty() {
    return h('div', { class: 'ds-empty-state' },
        h('div', { class: 'ds-empty-state-glyph' }, '( )'),
        h('p', { class: 'ds-empty-state-msg' }, 'fresh session, nothing said yet'),
        h('p', { class: 'ds-empty-state-hint' }, 'ask for code, markdown, an image, a pdf or a file attachment — or pick one of the prompts under "try" on the left and aicat answers in that shape.')
    );
}

function TranscriptError() {
    return h('div', { class: 'ds-alert ds-alert-error' },
        h('span', { class: 'ds-alert-icon' }, '!'),
        h('div', { class: 'ds-alert-content' },
            h('div', { class: 'ds-alert-title' }, 'aicat stopped mid-reply'),
            h('div', { class: 'ds-alert-message' }, 'the model returned a truncated response, so the last turn is incomplete rather than wrong-but-whole. your prompt is still in the box — resending replays it against a fresh context.'),
            h('div', { class: 'ds-alert-retry' },
                h('button', {
                    class: 'btn',
                    onclick: () => {
                        state.phase = 'ready';
                        const text = state.lastFailedText;
                        state.lastFailedText = null;
                        kit.render();
                        if (text) send(text);
                    }
                }, 'resend last turn')
            )
        )
    );
}

// Single source of truth for "conversation state" (thinking/purring/idle).
// Both headers previously computed this independently — the portrait read
// state.mood directly while the thread head hardcoded 'online · purring' —
// so they could (and did) disagree. Deriving both from state.mood here means
// there is exactly one place that decides what "online" currently means.
function liveStatus(s) {
    if (s.thinking) return 'thinking…';
    return s.mood === 'happy' ? 'online · purring' : 'online · idle';
}

// Folds the mascot identity (name + ASCII face, mood-driven) into the
// transcript's own head row instead of a separate standalone portrait block
// stacked above the chat panel — one section of vertical stacking removed
// ahead of the composer, matching a hero-composer layout where the composer
// is visible with no preceding avatar block. Reuses AICat's own `.chat-head`
// row chrome (passed as its `header` prop) so this stays visually identical
// to the thread head AICat renders by default, just with a face glyph added.
function AICatPortraitHead({ mood, status }) {
    return h('div', { class: 'chat-head aicat-portrait-head', role: 'banner' },
        h('pre', { class: 'aicat-face aicat-face-inline', role: 'img', 'aria-label': 'aicat portrait' }, FACES[mood] || FACES.idle),
        h('h2', { class: 'ds-chat-title' }, 'aicat'),
        h('span', { class: 'sub', 'aria-label': `status: ${status}` }, ' · ' + status),
        h('span', { class: 'spread' })
    );
}

function timeNow() { const d = new Date(); return String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0'); }

// Empty by default (matches the reference's empty-state-first canvas): the
// composer is the sole focal element on first load, with no seeded turns
// competing above it. The demo conversation is still reachable — the
// HISTORY row and the "say hi" suggestion chip both load WELCOME_MESSAGES.
const state = {
    draft: '', thinking: false, mood: 'idle', phase: 'ready', lastFailedText: null,
    messages: [],
    // Reference sidebar has a two-tab switcher above the project tree
    // (Projects / General) -- 'general' is a reachable reference tab (empty
    // placeholder state) rather than a second real section, since this kit
    // has exactly one real conversation surface, not two.
    sideTab: 'projects'
};

const root = document.getElementById('root');

function send(text) {
    // Guard against overlapping sends (rapid preset clicks / composer submits
    // while a reply is already in flight): without this, two concurrent
    // setTimeout chains both stamp receipt:'read' across every prior 'you'
    // message and both append a reply, corrupting the transcript's state
    // model even though every control involved is reachable and labelled.
    if (state.thinking) return;
    const sentIdx = state.messages.length;
    state.messages = [...state.messages, { who: 'you', avatar: 'u', time: timeNow(), receipt: 'delivered', parts: [{ kind: 'text', text }] }];
    state.draft = '';
    state.thinking = true;
    state.mood = 'think';
    kit.render();
    setTimeout(() => {
        state.thinking = false;
        state.mood = 'happy';
        const reply = classifyAndReply(text);
        state.messages = state.messages.map((m, i) => (m.who === 'you' && i === sentIdx) ? { ...m, receipt: 'read' } : m);
        state.messages = [...state.messages, { who: 'them', name: 'aicat', time: timeNow(), ...reply }];
        kit.render();
        setTimeout(() => { state.mood = 'idle'; kit.render(); }, 1400);
    }, 1100);
}

function App() {
    return AppShell({
        topbar: Topbar({ brand: '247420', leaf: 'aicat', items: [['index', '../../'], ['chat', '../chat/'], ['source', 'https://github.com/AnEntrypoint/design']] }),
        crumb: Crumb({ trail: ['247420', 'kits'], leaf: 'aicat' }),
        // Sidebar holds session/tree items only (new chat + a two-level
        // history tree). Preset prompts moved into the composer/empty-state
        // area as inline suggestion chips (see ChatSuggestions below) so the
        // sidebar reads as navigation, not a mixed nav+suggestions list.
        side: h('aside', { class: 'app-side', role: 'navigation', 'aria-label': 'sidebar navigation' },
            // Two-tab switcher above the tree (reference: Projects / General)
            // — reuses the existing .ds-filter-pill primitive already linked
            // by this sheet (see the phase-toggle group below) rather than
            // pulling in the heavier editor-tab-strip component for what is
            // a plain two-way toggle. 'general' is a real, reachable tab
            // (an empty-state placeholder), not a decoration.
            h('div', { class: 'ds-filter-pills aicat-side-tabs', role: 'tablist', 'aria-label': 'sidebar section' },
                h('button', {
                    type: 'button', role: 'tab', 'aria-selected': state.sideTab === 'projects' ? 'true' : 'false',
                    class: 'ds-filter-pill' + (state.sideTab === 'projects' ? ' active' : ''),
                    onclick: () => { state.sideTab = 'projects'; kit.render(); }
                }, 'Projects'),
                h('button', {
                    type: 'button', role: 'tab', 'aria-selected': state.sideTab === 'general' ? 'true' : 'false',
                    class: 'ds-filter-pill' + (state.sideTab === 'general' ? ' active' : ''),
                    onclick: () => { state.sideTab = 'general'; kit.render(); }
                }, 'General')
            ),
            state.sideTab === 'general' ? h('div', { class: 'app-side-group', role: 'group', 'aria-label': 'general' },
                h('p', { class: 'ds-side-empty-note' }, 'nothing here yet')
            ) : [
                Side({
                    sections: [
                        { group: 'session', items: [
                            { glyph: '+', label: 'new chat', key: 'new', onClick: (e) => {
                                e.preventDefault();
                                state.messages = [];
                                kit.render();
                                // Transient, non-blocking confirmation that the clear
                                // happened — "history" in the same sidebar group implies
                                // persistence, so a silent truncate reads as data loss
                                // rather than an intentional action taking effect.
                                const composerEl = root.querySelector('.chat-composer');
                                if (composerEl) flashComposerNote(composerEl, 'chat cleared');
                            } }
                        ] }
                    ]
                }),
                // History as a two-level project-tree: one expandable parent row
                // (native <details>, no bespoke expand/collapse JS needed) holding
                // individual past-conversation child rows. `.app-side-group`
                // reused for the outer chrome so heading rhythm matches Side()'s
                // own groups; child rows reuse `.app-side a` link styling via the
                // same anchor markup Side() emits, just nested one level deeper.
                h('div', { key: 'history-group', class: 'app-side-group', role: 'group', 'aria-label': 'history' },
                    h('details', { class: 'ds-side-tree', open: true },
                        h('summary', { class: 'ds-side-tree-summary' },
                            h('span', { class: 'glyph', 'aria-hidden': 'true' }, '~'),
                            h('span', {}, 'history'),
                            h('span', { class: 'count', 'aria-hidden': 'true' }, String(HISTORY.length))
                        ),
                        h('div', { class: 'ds-side-tree-children' },
                            ...HISTORY.map((item) => h('a', {
                                key: item.k,
                                href: '#',
                                class: 'ds-side-tree-child',
                                'aria-label': item.t,
                                // Reopens the seeded demo conversation rather than
                                // treating the row label as a fresh prompt to send —
                                // it reads as "history", so clicking it should
                                // rehydrate that past turn, not start a new one.
                                onclick: (e) => {
                                    e.preventDefault();
                                    if (state.thinking) return;
                                    state.messages = WELCOME_MESSAGES.map((m) => ({ ...m, time: timeNow() }));
                                    kit.render();
                                }
                            },
                                h('span', { class: 'glyph', 'aria-hidden': 'true' }, '·'),
                                h('span', {}, truncateAtWord(item.t, 26))
                            ))
                        )
                    )
                )
            ]
        ),
        main: [
            state.phase === 'ready' && state.messages.length === 0 ? (
                // True empty state matches the reference exactly: ONLY a
                // short lead question + bare composer, vertically centered,
                // nothing else on screen (no identity strip, no transcript
                // chrome, no suggestion chips, no docs fold) until the first
                // message lands. The populated branch below keeps all of
                // that — this is a genuinely different render, not a CSS
                // repositioning of the same block, because centering one
                // bundled block that still contains 5 other sections cannot
                // reproduce a page whose ENTIRE canvas is empty but for the
                // question and the input.
                h('div', { key: 'main-empty', class: 'ds-app-surface aicat-focus-col aicat-empty-canvas' },
                    h('div', { class: 'aicat-empty-hero' },
                        h('pre', { class: 'aicat-face aicat-face-hero', role: 'img', 'aria-label': 'aicat portrait' }, FACES.idle),
                        h('p', { class: 'aicat-empty-lead' }, 'what should aicat help with?')
                    ),
                    ChatComposer({
                        value: state.draft,
                        placeholder: 'ask aicat anything…',
                        disabled: state.thinking,
                        onInput: (v) => { state.draft = v; kit.render(); },
                        onSend: send
                    }),
                    // Reachable, clickable starting points -- an empty canvas
                    // with only a lead question and a bare input reads as
                    // broken/unfinished with nothing to click; these chips
                    // give a first-time visitor an obvious way in besides
                    // typing cold. Reuses the same ChatSuggestions primitive
                    // (and send()) as the populated state's "or try one of
                    // these" row below the transcript.
                    ChatSuggestions({
                        heading: 'try one of these',
                        suggestions: STARTER_PRESETS.map((p) => ({
                            id: p.k, label: truncateAtWord(p.q, 34),
                            onPick: () => { if (!state.thinking) send(p.q); }
                        }))
                    })
                )
            ) : h('div', { key: 'main-populated', class: 'ds-app-surface ds-section-pad aicat-focus-col' },
                // The transcript+composer is the dominant focal surface (a la
                // a centered hero composer): it renders FIRST, in a centered
                // max-width column (.aicat-focus-col, chat-polish.css), with
                // the mascot identity folded into the thread's own head row
                // (AICat's `header` prop) instead of a separate portrait
                // block stacked above it. Heading/lede/docs/dev-controls are
                // demoted below a fold so they no longer compete with it.
                state.phase === 'loading' ? Panel({ title: 'restoring session', children: TranscriptSkeleton() })
                : state.phase === 'error' ? Panel({ title: 'reply failed', children: TranscriptError() })
                : state.phase === 'empty' ? Panel({ title: 'new session', children: TranscriptEmpty() })
                : AICat({
                    name: 'aicat',
                    status: liveStatus(state),
                    header: AICatPortraitHead({ mood: state.mood, status: liveStatus(state) }),
                    messages: state.messages, thinking: state.thinking,
                    composer: ChatComposer({
                        value: state.draft,
                        placeholder: 'ask aicat anything…',
                        disabled: state.thinking,
                        onInput: (v) => { state.draft = v; kit.render(); },
                        onSend: send
                    })
                }),
                state.messages.length <= 2 ? ChatSuggestions({
                    heading: 'or try one of these',
                    suggestions: PRESETS.map((p) => ({
                        id: p.k, label: truncateAtWord(p.q, 34),
                        onPick: () => { if (!state.thinking) send(p.q); }
                    }))
                }) : null,
                // Heading/lede/docs/dev-controls demoted below a fold: a
                // first-time visitor's eye lands on the composer above, not a
                // marketing headline stack, matching a hero-composer layout.
                h('details', { class: 'ds-kit-controls' },
                    h('summary', {}, 'about this kit'),
                    h('div', { class: 'ds-kit-controls-body' },
                        Heading({ level: 2, children: 'aicat' }),
                        Lede({ children: 'an ai assistant with a cat persona. she replies in text, code (highlighted), markdown, images, pdfs, file attachments, or link cards — depending on what you ask.' }),
                        h('div', { class: 'ds-pattern-notes' },
                            h('p', {}, '· portrait swaps with mood — ', Chip({ tone: 'dim', children: 'idle' }), ' ', Chip({ tone: 'dim', children: 'think' }), ' ', Chip({ tone: 'accent', children: 'happy' }), '.'),
                            h('p', {}, '· thinking-state appends a typing bubble, disables the composer, blocks pre-emptive multi-sends.'),
                            h('p', {}, '· classifier in ', h('code', {}, 'classifyAndReply()'), ' is deterministic — wire it to your model, replies stay shaped as ', h('code', {}, '{parts:[…]}'), '.')
                        )
                    )
                ),
                // Dev/demo state toggles — reachable reference surface for the
                // transcript's other phases (loading/empty/error), but NOT
                // part of the "about this kit" documentation prose and not a
                // peer row inside the sidebar's `role="navigation"` landmark
                // (a first-time visitor scanning real nav rows next to a
                // debug "error" row could mistake it for a live system
                // alert). Collapsed by default behind a <details> disclosure —
                // the same pattern devtools/inspector-style panels in this
                // repo already use for opt-in secondary controls — so it
                // reads as scaffolding you can open, not live content.
                h('details', { class: 'ds-kit-controls' },
                    h('summary', {}, 'kit controls — transcript reference state'),
                    h('div', { class: 'ds-kit-controls-body' },
                        Lede({ children: 'switch the transcript panel above between its states —' }),
                        h('div', { class: 'ds-filter-pills', role: 'group', 'aria-label': 'transcript reference state' },
                            ...PHASES.map((p) => h('button', {
                                key: 'ph-' + p,
                                type: 'button',
                                class: 'ds-filter-pill' + (state.phase === p ? ' active' : ''),
                                'aria-pressed': state.phase === p ? 'true' : 'false',
                                onclick: () => {
                                    state.phase = p;
                                    if (p === 'error') {
                                        // Wire the reachable reference "error"
                                        // state to the same resend path a real
                                        // failure would take: fall back to the
                                        // last thing the user sent, or the
                                        // current draft, so "resend last turn"
                                        // has real text to replay.
                                        const lastYou = [...state.messages].reverse().find((m) => m.who === 'you');
                                        state.lastFailedText = (lastYou && lastYou.parts && lastYou.parts[0] && lastYou.parts[0].text) || state.draft || null;
                                    }
                                    kit.render();
                                }
                            }, p))
                        )
                    )
                )
            )
        ],
        status: Status({
            left: state.phase === 'ready'
                ? ['aicat', '- ' + state.messages.length + ' turns', state.thinking ? '- thinking' : '- idle']
                : ['aicat', '- ' + state.phase],
            right: ['247420 / mmxxvi']
        })
    });
}

const kit = mountKit({ root, view: App, screen: '07 AICat' });
window.__aicat = { state, render: kit.render, send };
