#!/usr/bin/env node
// WCAG 2.1 AA compliance guard: headless-browser-loads every real preview/*.html
// demo page and runs the real axe-core engine against the live, rendered DOM
// (not a static-HTML heuristic scan -- axe needs computed styles/contrast,
// which only exist post-render). Reuses generate-preview-index.mjs's own
// preview-page enumeration so this never drifts from what that script lists.
// Wired as a build.mjs step (matching the CI-blocking pattern lint-tokens.mjs
// already uses): a real violation fails the build, not just prints a report.
import { readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { chromium } from 'playwright'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const previewDir = join(root, 'preview')
const axeCorePath = fileURLToPath(new URL('../node_modules/axe-core/axe.min.js', import.meta.url))

// Same enumeration generate-preview-index.mjs uses (readdirSync + filter),
// duplicated rather than imported since that script's own top-level code
// writes preview/index.html as a side effect on import -- importing it here
// would silently regenerate that file as an unrelated side effect of running
// the a11y audit. Kept in lockstep by both filtering the exact same pattern.
function listPreviewFiles() {
    return readdirSync(previewDir)
        .filter(f => f.endsWith('.html') && f !== 'index.html')
        .sort()
}

export async function auditAllPreviews({ onProgress } = {}) {
    const files = listPreviewFiles()
    const browser = await chromium.launch()
    const results = []
    try {
        for (const file of files) {
            const page = await browser.newPage()
            try {
                await page.goto(pathToFileURL(join(previewDir, file)).href, { waitUntil: 'networkidle' })
                await page.addScriptTag({ path: axeCorePath })
                const axeResult = await page.evaluate(() => window.axe.run(document, {
                    // WCAG 2.1 AA per the row's own stated target.
                    runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'] },
                }))
                results.push({ file, violations: axeResult.violations, passCount: axeResult.passes.length })
                if (onProgress) onProgress(file, axeResult.violations.length)
            } finally {
                await page.close()
            }
        }
    } finally {
        await browser.close()
    }
    return results
}

function summarize(results) {
    const totalViolations = results.reduce((sum, r) => sum + r.violations.length, 0)
    const filesWithViolations = results.filter(r => r.violations.length > 0)
    return { totalViolations, fileCount: results.length, filesWithViolations: filesWithViolations.length }
}

function writeReport(results) {
    const lines = []
    lines.push(`# a11y audit report (WCAG 2.1 AA)`)
    lines.push(``)
    lines.push(`Generated by scripts/a11y-audit.mjs. Re-run: node scripts/a11y-audit.mjs`)
    lines.push(``)
    const s = summarize(results)
    lines.push(`${s.fileCount} preview pages scanned, ${s.totalViolations} total violation(s) across ${s.filesWithViolations} page(s).`)
    lines.push(``)
    for (const r of results) {
        if (!r.violations.length) continue
        lines.push(`## ${r.file}`)
        for (const v of r.violations) {
            lines.push(`- **${v.id}** (${v.impact}): ${v.help} -- ${v.nodes.length} node(s)`)
            lines.push(`  ${v.helpUrl}`)
        }
        lines.push(``)
    }
    mkdirSync(join(root, 'docs'), { recursive: true })
    writeFileSync(join(root, 'docs', 'a11y-report.md'), lines.join('\n'))
}

// CLI entry guard -- importable as a module (auditAllPreviews) without
// triggering the real browser run + build-failing exit code.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    const results = await auditAllPreviews({ onProgress: (file, count) => console.log(`[a11y-audit] ${file}: ${count} violation(s)`) })
    writeReport(results)
    const s = summarize(results)
    console.log(`[a11y-audit] ${s.fileCount} pages scanned, ${s.totalViolations} violation(s) across ${s.filesWithViolations} page(s). Report: docs/a11y-report.md`)
    if (s.totalViolations > 0) {
        console.error(`[a11y-audit] FAILING BUILD: ${s.totalViolations} WCAG 2.1 AA violation(s) found`)
        process.exit(1)
    }
}
